services:
  docker:
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - .:/app
    command: tail -f /dev/null
